site_name: Noscrape
site_dir: docs
docs_dir: src
theme:
  name: readthedocs
  custom_dir: 'custom_theme'
  highlightjs: true
  hljs_languages:
    - javascript
    - php
    - java
    - console
    - shell
extra_javascript:
  - "js/analytics.js"
nav:
  - "Welcome": 'index.md'
  - "Use-Cases": 'use-cases.md'
  - "Usage":
    - "Java": 'java.md'
    - "PHP": 'php.md'

