site_name: Noscrape
site_dir: docs
docs_dir: src
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - javascript
    - php
    - java
    - console
    - shell

nav:
  - "Welcome": 'index.md'
  - "Usage":
    - "Java": 'java.md'
    - "PHP": 'php.md'

