site_name: Noscrape
site_dir: docs
site_url: "https://noscrape.github.io"
site_author: "Bernhard Schönberger"
site_description: "Documentation about Noscrape-Library"
docs_dir: src
theme:
  name: readthedocs
  custom_dir: 'custom_theme'
  highlightjs: true
  hljs_languages:
    - javascript
    - php
    - java
    - console
    - shell
extra_javascript:
  - "js/analytics.js"
nav:
  - "Introduction": 'index.md'
  - "Use Cases": 'use-cases.md'
  - "NON-Use Cases": 'non-use-cases.md'
  - "Usage":
    # - "Java": 'java.md'
    - "NodeJS": 'nodejs.md'
    - "PHP": 'php.md'

